/*
 * Organiser Application API
 * Organiser application made for learning Java
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pl.jacek.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Meeting
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2021-04-09T11:54:42.656Z")
public class Meeting   {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("date")
  private String date = null;

  @JsonProperty("participants")
  private List<Participant> participants = new ArrayList<Participant>();

  public Meeting id(Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Meeting id
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(required = true, value = "Meeting id")
  @NotNull
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Meeting name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Meeting name
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(required = true, value = "Meeting name")
  @NotNull
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Meeting date(String date) {
    this.date = date;
    return this;
  }

  /**
   * Meeting date
   * @return date
   **/
  @JsonProperty("date")
  @ApiModelProperty(required = true, value = "Meeting date")
  @NotNull
 @Pattern(regexp="/([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/")  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public Meeting participants(List<Participant> participants) {
    this.participants = participants;
    return this;
  }

  public Meeting addParticipantsItem(Participant participantsItem) {
    this.participants.add(participantsItem);
    return this;
  }

  /**
   * Get participants
   * @return participants
   **/
  @JsonProperty("participants")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  @Valid
  public List<Participant> getParticipants() {
    return participants;
  }

  public void setParticipants(List<Participant> participants) {
    this.participants = participants;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Meeting meeting = (Meeting) o;
    return Objects.equals(this.id, meeting.id) &&
        Objects.equals(this.name, meeting.name) &&
        Objects.equals(this.date, meeting.date) &&
        Objects.equals(this.participants, meeting.participants);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, date, participants);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Meeting {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    participants: ").append(toIndentedString(participants)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

